### ISSUE TITLE
import statement error on Node v12.22.7

### ISSUE THREAD

**Issue by GemKosan** [evelynhathaway/jest-location-mock#121]
I get the following error when I try to jest against one of my unit test files after adding jest-location-mock to my jest-setup.js.
"Cannot use import statement outside a module”

jest-location-mock v1.0.1
Node v12.22.7
Jest v26.6.3

Also - I can't install the latest version of jest-location-mock, because npm can't find v3.0.0 of @jedmao/location.

Please help!

**Comment by evelynhathaway** [comment]
Hmmm. I'd like to look into this for you, but am unsure what I should be trying to reproduce here. Some clarification should help us get this all fixed up.

Are you on Node.js v16.x or v12.22.7? I notice there are two different versions mentioned in this issue.

What is the error that npm gives trying to install `@jedmao/location`? It is on the public npm registry at that version, so I am unsure if it's a local package resolution issue or maybe your setup can't use the public registry for some scopes.

For the `"Cannot use import statement outside a module”` error, could you post the full error? My first guess is that you are not using a version of Jest and Node that can support ESM natively, and aren't using a transformer like ts-jest or babel for the rest of your code. If my assumption is correct, [the setup file](https://github.com/evelynhathaway/jest-location-mock#setup) should be a require like the below until you start using ESM imports in your tests:

**`config/jest-setup.js`**

```js
// Mock `window.location` with Jest spies and extend expect
require("jest-location-mock");
```

**Comment by GemKosan** [comment]
Thanks! Let me see...

Node is v12.22.7. I've updated the issue name.

### ESM
So, in order to get the jest-location-mock npm to install, I need to install `jest-location-mock v1.0.1` and `@jedmao/location installs v2.0.4` (see 2nd heading below).

I don't think I'm running ESM natively, but I am running React JS with `webpack v5.36.2`, `typescript v4.2.4`, `jest v26.6.3`, and `babel-jest v26.6.3`. When I try to run jest on a .test.tsx file, I get this error:

> FAIL  src/components/Alert/Alert.test.tsx
>   ● Test suite failed to run
> 
>     Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
> 
>     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
> 
>     Here's what you can do:
>      • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
>      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
>      • If you need a custom transformation specify a "transform" option in your config.
>      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
> 
>     You'll find more details and examples of these config options in the docs:
>     https://jestjs.io/docs/en/configuration.html
> 
>     Details:
> 
>     /Users/gkosan/indeed/jobman-core-modules/node_modules/jest-location-mock/lib/index.js:2
>     import "./extend-expect";
>     ^^^^^^
> 
>     SyntaxError: Cannot use import statement outside a module
> 
>       1 | import '@testing-library/jest-dom/extend-expect';
>     > 2 | import 'jest-location-mock';
>         | ^
>       3 | import { configure } from 'enzyme';
>       4 | import Adapter from 'enzyme-adapter-react-16';
>       5 |
> 
>       at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
>       at Object.<anonymous> (jest.setup.js:2:1)

A colleague suggested I add your package to my `jest.config.js` under transformIgnorePatterns (there is no transform property defined in the file):
`transformIgnorePatterns: ['node_modules/(?!(jest-location-mock))'],`
When I do that, running jest produces a different error:

> FAIL  src/components/Alert/Alert.test.tsx
>   ● Test suite failed to run
> 
>     TypeError: Cannot read property 'prototype' of undefined
> 
>       1 | import '@testing-library/jest-dom/extend-expect';
>     > 2 | import 'jest-location-mock';
>         | ^
>       3 | import { configure } from 'enzyme';
>       4 | import Adapter from 'enzyme-adapter-react-16';
>       5 |
> 
>       at _inheritsLoose (node_modules/@babel/runtime/helpers/inheritsLoose.js:4:49)
>       at node_modules/jest-location-mock/lib/utils/location-mock-relative.js:13:31
>       at Object.<anonymous> (node_modules/jest-location-mock/lib/utils/location-mock-relative.js:34:2)
>       at Object.<anonymous> (node_modules/jest-location-mock/lib/utils/index.js:1:1)
>       at Object.<anonymous> (node_modules/jest-location-mock/lib/matchers/to-be-at.js:2:1)
>       at Object.<anonymous> (node_modules/jest-location-mock/lib/matchers/index.js:1:1)
>       at Object.<anonymous> (node_modules/jest-location-mock/lib/extend-expect.js:2:1)
>       at Object.<anonymous> (node_modules/jest-location-mock/lib/index.js:2:1)
>       at Object.<anonymous> (jest.setup.js:2:1)

### @jedmao/location
When I do a npm install, @jedmao/location installs at v2.0.4 (see attached package.json).
[package.json.txt](https://github.com/evelynhathaway/jest-location-mock/files/7677480/package.json.txt)

If I ask npm to install v3.0.0, it acts like that version doesn't exist:

> gkosan@IT-USA-VX3456 jobman-core-modules % npm install @jedmao/location@3.0.0 
> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for @jedmao/location@3.0.0.
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/gkosan/.npm/_logs/2021-12-08T16_28_45_842Z-debug.log
> 
> npm failed, show the debug log of the indeed npm wrapper:
> command executed: npm install @jedmao/location@3.0.0
> command npm  install @jedmao/location@3.0.0

See attached npm log:
[2021-12-08T16_28_45_842Z-debug.log](https://github.com/evelynhathaway/jest-location-mock/files/7677489/2021-12-08T16_28_45_842Z-debug.log)

**Comment by evelynhathaway** [comment]
Thank you that information, that comment was very helpful!

### ESM

Ah yes, since you are on version `v1.0.1`, this error can still occur since `node_modules` isn't transformed. If you update to `v1.0.2` or above (I recommend using `v1.0.9` if possible), we should be left with the issue installing the `@jedmao/location` dependency.

### @jedmao/location

The npm log reveals that this package is being fetched from your company npm registry.

There are a number of possible issues that could cause this, like [being on an outdated version of Nexus](https://issues.sonatype.org/browse/NEXUS-6857?focusedCommentId=334109&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-334109), the registry being configured to whitelist certain public modules or scopes, the registry being completely private, etc..

While not a permanent fix, you can try narrowing down the issue by fetching this package from the public registry. Running the below command on your local development machine or an `.npmrc` file may help.

```bash
npm config set @jedmao:registry https://registry.npmjs.org/
```

If installing the `@jedmao/location` package succeeds using the public registry, I would send your failing npm log to your the team that manages the Nexus registry at your company (DevOps/SRE). They should be able to provide more insight to how the registry is configured and browse the packages on that registry.

If it still fails, I would run `npm config list` and compare them to working configurations. Your company onboarding or runbook documents may provide some insight to the disired configuration, and below is a working configuration also from a Mac running the same version of Node.js and npm via nvm:

```
$ npm config list

; cli configs
metrics-registry = "https://artifactory.REDACTED_COMPANY.com/api/npm/et-npm/"
scope = ""
user-agent = "npm/6.14.15 node/v12.22.7 darwin x64"

; userconfig /Users/REDACTED_USERNAME/.npmrc
@REDACTED_COMPANY_NPM_SCOPE:registry = "https://artifactory.REDACTED_COMPANY.com/api/npm/et-npm/"
always-auth = true
registry = "https://registry.npmjs.org/"

; node bin location = /Users/REDACTED_USERNAME/.nvm/versions/node/v12.22.7/bin/node
; cwd = /Users/REDACTED_USERNAME/test
; HOME = /Users/REDACTED_USERNAME
; "npm config ls -l" to show all defaults.
```

The private Artifactory npm registry I tested with is a proxy of the entire public registry, so I was able to install the package as shown above as well as with `registry = "https://artifactory.REDACTED_COMPANY.com/api/npm/et-npm/"`.

I hope this helps!

**Comment by GemKosan** [comment]
Updating to the latest versions of @jedmao/location and jest-location-mock solved the issue.
Thanks, @evelynhathaway !
